version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./docker/volumes/postgres:/var/lib/postgresql/data
  app:
    build:
      context: .
      args:
        RAILS_ENV: development
    environment:
      - APP_ENV=development
      - APPLICATION_NAME=default_sinatra
      - DATABASE_HOST=db
    volumes:
      - .:/opt/default_sinatra
    ports:
      - "9292:9292"
    depends_on:
      - db
