development:
  key: default_sinatra_development
  secret: kl978GD8g328uyasg8fgu2ig9asgfuG9
  expire: 86400
test:
  key: default_sinatra_test
  secret: 98G723GI*78g329g8asdf2349gausdgs
production:
  key: default_sinatra_production
  secret: 329G9UI0H089g2bkadg8730pvxDmqw9s
  expire: 86400
