development:
  adapter: mysql2
  database: default_sinatra
  username: root
  password:
  host: localhost
  port: 3306
  pool: 5
test:
  adapter: mysql2
  database: default_sinatra_test
  username: root
  password:
  host: localhost
  port: 3306
  pool: 20
production:
  adapter: mysql2
  database: default_sinatra
  username: root
  password:
  host: localhost
  port: 3306
  pool: 20
