default: &default
  adapter: postgresql
  host: <%= ENV.fetch('DATABASE_HOST', 'localhost') %>
  port: <%= ENV.fetch('DATABASE_PORT', '5432') %>
  database: <%= ENV.fetch('APPLICATION_NAME').downcase %>_<%= ENV.fetch('APP_ENV') %>
  username: <%= ENV.fetch('DATABASE_USERNAME', 'postgres') %>
  password: <%= ENV.fetch('DATABASE_PASSWORD', 'postgres') %>
  pool: <%= ENV.fetch('DATABASE_POOL') { 5 } %>
  timeout: 5000
  reconnect: true

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
